insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('下列哪一个不是组成计算机的必要硬件？','硬盘','中央处理器','独立显卡','内存条',3);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('下列哪个型号的CPU性能是最好的？','I3-4330','I5-6500','I7-6770','I7-7500',4);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('笔记本拆机一般是从哪两个面拆机？','A面和B面','B面和C面','C面和D面','D面和A面',3);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('笔记本拆机的第一步应该是？','卸下电池','拆下螺丝','拆下后盖','拆下键盘',1);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('在英伟达独立显卡中下列性能最好的是?','9800GT','GTX 970','GTX 980M','GTX 1070',4);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('下列说法正确的是?','在为自己的电脑升级内存时，加的内存容量越大电脑越快','在台式机装机的时候，把主板安装进机箱的步骤应放在安装挡板后','在安装CPU的时候，需要比较用力地将CPU针脚插入主板的插槽中','在笔记本拆机清灰后重新添加硅脂时，我们需要涂多一些，以提高CPU的散热性能',2);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values (' IPv6是Internet Protocol Version 6的缩写，其中Internet Protocol译为“互联网协议”。是用于替代现行版本IP协议（IPv4）的下一代IP协议，号称可以为全世界的每一粒沙子编上一个网址。以下说法错误的是：','我们现在用的是IPV4','现在还没普及的原因是线路铺设成本较高','宿舍里可以用IPV6','IPv6的使用，可以解决网络地址资源数量的问题',3);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values (' 域名虽然便于人们记忆，但机器之间只能互相认识IP地址，它们之间的转换工作称为域名解析，域名解析需要由专门的域名解析服务器来完成，下列哪个是域名解析服务器？','DNS','DHCP','IPS','VPS',1);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('下列哪个命令可以显示所有网络适配器（网卡、拨号连接等）的完整TCP/IP配置信息？','ipconfig /all','iconfig /all','ip all','ipconfig /everything',1);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('下列哪个是ip地址','222.666.233.0','233.233.233.1','1023.222.11.1','192.168.256.1',2);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('以下哪种方法不可以用于翻墙？',' VPN',' 代理服务器','修改hosts','修改电脑上的ip地址',4);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values (' 以下人物谁是中国国家防火墙（GFW）之父？','方滨兴','吴恩达','任正非','刘强东',1);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('以下关于HTTP和HTTPS的叙述错误的是？',' HTTP协议以明文方式发送内容','HTTP协议适合传输一些敏感信息','HTTPS可提供加密服务','安全性好的网站多数以https开头',2);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('电脑能上QQ，不能上网 ，我们应该如何解决？请选出最简单的方式','假装没看见','查看电脑的DNS有没有设置正确','重装系统','再买一台电脑',2);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('在命令提示符界面中，如何停止某个正在运行的命令？','ctrl+c','alt+c','ctrl+v','win+a',1);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('勒索病毒来袭，如何正确防范？','安装最新更新，关闭相应端口，下载有名的杀毒软件防范','打开相应端口','坐以待毙','汇钱保平安',1);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('电脑按下开机键没有反应可能是什么问题','BIOS电池没电','硬盘接口松动','BIOS设置问有题','有静电',3);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('连不上ZJUWLAN可以尝试以下操作除了','netsh winsock reset','ipconfig /flushdns','查看代理','查看task manager',4);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('下列哪个不能做到电脑防护','Ccleaner','卡巴斯基','Windows defender','小红伞',1);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('数据误删了可以用什么','Usbcleaner','Windowsdefender','Ccleaner','EasyRecovery',4);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('在文印店中毒了文件没了怎么办','Usbcleaner','Windowsdefender','Ccleaner','EasyRecovery',1);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('下列哪项不是使用机械硬盘的注意事项','减少抖动','严禁运转时撞击或移动硬盘','不可进行碎片整理','强制关机会损伤硬盘',3);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('下列关于固态硬盘说法错误的是','不建议进行碎片整理','存储颗粒可分为三大类','主控芯片对其性能影响不大','采用分布式存储机制',3);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('下列哪种做法可以进入bios','开机时长按键盘上某个键','开机时连续按某个键','插上带PE的u盘就可以进','长按电源键',2);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('进入PE后在系统运行时如果需要拔掉U盘该怎么做?','直接拔掉','选择弹出后再拔掉','格式化后再拔掉','找到PE管理工具后选择弹出',1);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('在PE中的windows安装器中，选择文件时可行的是:','选WIM文件,使用左键点击','选ISO文件,使用左键点击','选OEM文件,使用右键点击','选择IOS文件使用右键点击',1);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('在格式化硬盘时，4K分区是指？','对齐分区到512扇区数的整数倍','对齐分区到1024扇区数的整数倍','对齐分区到2048扇区数的整数倍','对齐分区到4096扇区数的整数倍',4);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('不能进入PE可能是bios里哪个选项未关闭','secure boot','PXE Boot to LAN','Intel Virtualization Technology','AC Mode Fan always on',1);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('下列说法正确的是?','将u盘做成PE盘时，微PE工具箱需要放在U盘里方便提取','在PE的windows安装器工具中有三个指示灯，如果其中有黄灯就不能继续装系统','装完win7系统后不需要自己装驱动，连上网可以自动装驱动','u盘做成PE盘以后可以日常使用',4);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('最为常见的充电式led台灯损坏的原因不包括','插头与插孔接触不良','电池寿命已到','灯泡烧坏或开关损坏','内部电阻丝损坏',4);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('下列关于焊锡膏的作用叙述不正确的是','去除PCB铜膜焊盘表层及零件焊接部位的氧化物质，便于上锡。','保护和防止焊后PCB再度氧化。','降低锡、铅表面张力，降低焊点缺陷率。','改变焊锡的化学组成，提高焊点的延展性。',4);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('下列哪一项不属于寝室安全用电的具体细则？','电器使用完后应拔掉电源插头或关闭接线板上的开关','电源接线板不应该放在床上，应放在书桌安全处，原理易燃物品','在断掉跳闸时可以随意搬动电闸企图通电。','不随意在寝室更改、拆卸、安装电源电路、插座、插头等',3);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('焊接什么元件时，烙铁必须接地？','MOS管','电解电容','瓷片电容','可变电阻',1);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('焊接的一般步骤为','加热焊盘 送入焊锡丝 移开焊锡丝 移开烙铁','送入焊锡丝 加热焊盘 移开烙铁 移开焊锡丝','送入焊锡丝 加热焊盘 移开焊锡丝 移开烙铁','加热焊盘  送入焊锡丝 移开烙铁 移开焊锡丝',1);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('USB接口的供电电压为','1.5V','3.3V','5V','12V',3);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('当焊接失误，需要拆焊操作时候，除了电烙铁，我们需要用到的工具是','焊锡膏','吸锡器','焊锡丝','热胶枪',2);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('电吹风的电路元件不包括','电阻丝','稳压二极管','电机','热敏电阻',4);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('在焊接的准备、插件过程中，以下哪一步不是合理的？','安装元器件前，认真查看元器件的外观和标称值，通过仪器检查元器件的参数和性能。','在插入元件时提前剪掉过长的引脚。','元件根据外形和管脚间距弯曲成合理的形状。','先低后高，先轻后重，先易后难。',2);
insert into question(Stem,Select_1,Select_2,Select_3,Select_4,Select_Right) values ('以下关于焊接过程的注意事项，正确的是','清洁电烙铁所使用的海绵应沾有适量的稀盐酸。','焊接过程中，可直接用手辅助固定焊接元件。','烙铁温度过低、焊盘氧化或者有油污，容易造成虚焊。','烙铁头氧化后用可以用锉刀打磨。',3);
